SECRET: str = "python"
guess: str = input(f"What is your {len(SECRET)}-letter guess? ").lower()
playing: bool = True
WHITE_BOX: str = "\U00002B1C"
GREEN_BOX: str = "\U0001F7E9"
YELLOW_BOX: str = "\U0001F7E8"
index: int = 0
accuracy: str = ""
misplaced: bool = False
secret_index: int = 0
